enum_discrim_align_threshold = 30
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
inline_attribute_width = 50
match_arm_leading_pipes = "always"
merge_imports = true
reorder_impl_items = true
report_fixme = "Always"
report_todo = "Always"
use_field_init_shorthand = true
use_small_heuristics = "Max"
where_single_line = true
